# .github/workflows/test.yml

name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.3

    - name: Install dependencies
      run: go mod download

    - name: Build and test
      run: go test ./...

    - name: Lint
      run: golangci-lint run